/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_serialport_api_SerialPort */

#ifndef _Included_com_mdeveloper_serialtool_Serial
#define _Included_com_mdeveloper_serialtool_Serial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_serialport_demo_serialport_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_mdeveloper_serialtool_Serial_Open
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_serialport_demo_serialport_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mdeveloper_serialtool_Serial_Close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
